[build]
publish = "."
command = "npm install"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"
included_files = ["node_modules/@netlify/blobs/**"]

[build.environment]
NODE_VERSION = "20"
