# clinic-queue-netlify-git/netlify.toml

[build]
  publish = "."
  functions = "netlify/functions"

# Map /api/* to your serverless functions  
[[redirects]]
from = "/api/*"
to   = "/.netlify/functions/:splat"
status = 200
force = true
